spring:
  application:
    name: products-microservice
  jmx:
    default-domain: products-microservice

eureka:
  instance:
    non-secure-port: 8080
    instance-id: localhost
    prefer-ip-address: true
    non-secure-port-enabled: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    prefer-same-zone-eureka: true
    use-dns-for-fetching-service-urls: false