spring:
  application:
    name: products-microservice
  jmx:
    default-domain: products-microservice

server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true
