spring:
  application:
    name: eureka
  jmx:
    default-domain: eureka

server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    non-secure-port: 8761
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
