spring:
  application:
    name: discovery-microservice
  jmx:
    default-domain: discovery-microservice

server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    non-secure-port: 8761